name: Java CI with Maven and Allure Report

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Install Chrome
        uses: selenide/actions/setup-selenide@v1
        with:
           browser: chrome
           browser-version: latest
           args: --headless


      - name: Build the Project
        run: mvn clean install -DskipTests

      - name: Run regression suite
        run: mvn clean test

  allure_report:
    name: Generate and Deploy Allure Report
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
